<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvCZViZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvCZViZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRvCZViZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRvCZViZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRvCZViZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'RvCZViZ',
    'container.build_id' => 'cd359284',
    'container.build_time' => 1699659705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvCZViZ');
